name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.10
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - tqdm
  - pip
  - pip:
    - opencv-python
    - joblib
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
